version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: app.dockerfile
    volumes:
      - .:/var/www
    expose:
      - "9000"
    depends_on:
      - database

  web:
    build:
      context: .
      dockerfile: web.dockerfile
    volumes:
      - .:/var/www
      - ./vhost.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app

  database:
    image: mysql:8.0
    environment:      
      DB_HOST: database
      MYSQL_ROOT_PASSWORD: itdhg
      MYSQL_DATABASE: po
    ports:
      - "33061:3306"
